services:
  nginx:
    image: nginx:1.19.5
    networks:
      - network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./staticfiles:/staticfiles
      - ./media:/usr/src/app/media
    expose:
      - "80"
    ports:
      - "80:80"
    depends_on:
      - cms_admin

  cms_admin:
    build:
      context: .
      dockerfile: Dockerfile
    image: "cms_admin:${VERSION}"
    container_name: "cms_admin"
    networks:
      - network
    volumes:
      - ./staticfiles:/staticfiles
      - ./media:/usr/src/app/media
    entrypoint:
      - sh
      - docker-entry.sh
    ports:
      - "8000:8000"
    expose:
      - "8000"
    restart: always

networks:
  network:
    driver: bridge