# Generated by Django 5.0.4 on 2024-05-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms_base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="url",
            field=models.FileField(
                max_length=255, upload_to="attachments", verbose_name="첨부파일"
            ),
        ),
    ]
